site_name: DCAN Labs NDA BIDS Upload Tool
theme: readthedocs
plugins:
  - search
docs_dir: docs
nav:
  - Overview: index.md
  - 1. Install Dependencies: dependencies.md
  - 2. Create Your Uploads Working Directory: workingdirectory.md
  - 3. Prepare the lookup CSV: lookup.md
  - 4. Create YAML and JSON files: metadatafiles.md
  - 5. Run prepare and upload scripts: scripts.md
  - 6. Advice for Working with the NDA: nda.md
  - 7. Additional Information: additionalinformation.md
